version: '2'
services:

  silk:
    build: ./build/silk
    restart: always
    logging:
      driver: fluentd
      options:
        fluentd-address: "${FLUENTD_SERVER}:24224"
        tag: "docker.silk"
        fluentd-async-connect: "true"
    ports:
      - 514:514
      - 514:514/udp
    #environment:
      #FLUENTD_CONF: "fluentd-syslog.conf"
      #FLUENTD_OPT: "-vv"
      #ES_SERVER: ${ES_SERVER1} # Server to connect to and load ES Templates
      #ES_SERVER2: ${ES_SERVER2} # Secondary Server, set to same as Primary if you don't have one
      #ES_USER: "elastic" # Username used to connect to ES to load Templates
      #ES_PASSWORD: "changeme" # Password used to connect to ES to load Templates
    #volumes:
      #- ${DOCKER_DATA}/docker-azure-fluentd/fluentd-receiver/config:/fluentd/etc
      #- ${DOCKER_DATA}/docker-azure-fluentd/fluentd-receiver/data:/data_log
      #- ${DOCKER_DATA}/docker-azure-fluentd/fluentd_buffer/syslog:/fluentd_buffer
    cap_add:
      - NET_BIND_SERVICE
    networks:
      - main

networks:
  main:
