version: '2'
services:

  silk:
    build: ./build/silk
    restart: always
    logging:
      driver: fluentd
      options:
        fluentd-address: "${FLUENTD_SERVER}:24224"
        tag: "docker.silk"
        fluentd-async-connect: "true"
#    ports:
#      - 514:514
#      - 514:514/udp
#    environment:
#      SILK_SENSOR0: ${SILK_SENSOR0}
#      SILK_SENSOR1: ${SILK_SENSOR1}
#      SILK_SENSOR2: ${SILK_SENSOR2}
    volumes:
      - ${DOCKER_DATA}/docker-silk-standalone/silk/data:/data
      - ${DOCKER_CONFIG}/docker-silk-standalone/silk/config:/config
#    cap_add:
#      - NET_BIND_SERVICE
    networks:
      - main

networks:
  main:
